# Generated by Django 5.0 on 2023-12-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_alter_castpath_id_alter_cinema_cinema_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="Room_max_col",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="Room_max_row",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
