# Generated by Django 5.0 on 2023-12-28 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_alter_movie_movie_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seat",
            name="Seat_state",
        ),
        migrations.CreateModel(
            name="Seat_in_session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Seat_State", models.IntegerField(blank=True, null=True)),
                (
                    "Seat_ID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.seat",
                    ),
                ),
                (
                    "Session_ID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.session",
                    ),
                ),
            ],
        ),
    ]
