# Generated by Django 5.0 on 2023-12-30 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_remove_seat_seat_state_seat_in_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="Session_ID",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="Seat_ID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.seat_in_session",
            ),
        ),
    ]
