# Generated by Django 5.0 on 2023-12-22 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cinema",
            fields=[
                ("Cinema_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Cinema_name", models.TextField()),
                ("Cinema_location", models.TextField()),
                ("Cinema_description", models.TextField()),
                ("Cinema_image", models.TextField()),
                ("Cinema_closing", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("Movie_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Movie_title", models.TextField()),
                ("Movie_category", models.TextField()),
                ("Movie_description", models.TextField()),
                ("Movie_duration", models.FloatField(blank=True, null=True)),
                ("Movie_director", models.TextField()),
                ("Movie_path", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=50)),
                ("title", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("User_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("User_name", models.TextField()),
                (
                    "User_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "User_password",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("User_phone_number", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ImagesPath",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Image_path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "Movie_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.movie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CastPath",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Actor_path", models.CharField(blank=True, max_length=255, null=True)),
                ("actor_name", models.TextField()),
                (
                    "Movie_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.movie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("Room_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Room_number", models.IntegerField(blank=True, null=True)),
                ("Room_capacity", models.IntegerField(blank=True, null=True)),
                (
                    "Cinema_ID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.cinema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                ("Seat_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Seat_reference", models.TextField()),
                ("Seat_state", models.IntegerField(blank=True, null=True)),
                (
                    "Room_ID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("Session_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Session_time", models.DateTimeField(blank=True, null=True)),
                ("Session_version", models.TextField()),
                ("Session_price", models.IntegerField(blank=True, null=True)),
                (
                    "Session_movie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.movie",
                    ),
                ),
                (
                    "Session_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ticket_time", models.DateTimeField(blank=True, null=True)),
                ("Ticket_barcode", models.TextField()),
                (
                    "Seat_ID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.seat",
                    ),
                ),
                (
                    "Session_ID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.session",
                    ),
                ),
                (
                    "User_ID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.user",
                    ),
                ),
            ],
        ),
    ]
