# Generated by Django 5.0 on 2023-12-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_room_room_max_col_room_room_max_row"),
    ]

    operations = [

    ]
