# Generated by Django 5.0 on 2024-01-02 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
