# Generated by Django 5.0 on 2023-12-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_alter_movie_movie_duration"),
    ]

    operations = [

    ]
