# Generated by Django 5.0 on 2024-01-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imagespath",
            old_name="Image_path",
            new_name="Image",
        ),
        migrations.AddField(
            model_name="movie",
            name="Image_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="Movie_duration",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
