# Generated by Django 5.0 on 2023-12-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0006_alter_movie_movie_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="Movie_duration",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
