# Generated by Django 5.0 on 2024-01-02 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "backend",
            "0006_rename_image_path_imagespath_image_movie_image_path_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="Movie_duration",
        ),
    ]
