# Generated by Django 5.0 on 2024-01-02 23:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_movie_movie_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="Movie_duration",
        ),
    ]
