# Generated by Django 5.0 on 2024-01-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0009_remove_movie_movie_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="Movie_duration",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
