# Generated by Django 5.0 on 2024-01-09 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0010_movie_movie_duration"),
        ("backend", "0011_movie_image_path_token"),
    ]

    operations = []
