# Generated by Django 5.0 on 2024-01-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0012_merge_20240109_1134"),
    ]

    operations = [

        migrations.AlterField(
            model_name="ticket",
            name="Ticket_barcode",
            field=models.TextField(blank=True, null=True),
        ),
    ]
