# Generated by Django 5.0 on 2024-01-09 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0014_user_user_token"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Token",
        ),
    ]
