# Generated by Django 5.0 on 2024-01-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0016_remove_user_user_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="User_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
