# Generated by Django 5.0 on 2024-01-09 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0017_user_user_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="User_token",
            new_name="User_Mytoken",
        ),
    ]
