# Generated by Django 5.0 on 2024-01-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0018_rename_user_token_user_user_mytoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="FCM_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
